# Worker DCSMachineTemplate.
# Official required disks for worker:
#   systemVolume, /var/lib/kubelet 100G, /var/lib/containerd 100G.
# This environment: template slem-alaudaos-vda, folder ACP_Cluster.
# No /var/lib/etcd on workers. /var/cpaas is on the worker IP pool.
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: DCSMachineTemplate
metadata:
  name: dcs-workloadcluster-worker-template
  namespace: cpaas-system
spec:
  template:
    spec:
      vmTemplateName: slem-alaudaos-vda
      location:
        type: folder
        name: ACP_Cluster
      vmConfig:
        dvSwitchName: ManagementDVS
        portGroupName: VLAN-329
        dcsMachineCpuSpec:
          quantity: 8
        dcsMachineMemorySpec:
          quantity: 16384
        dcsMachineDiskSpec:
          - quantity: 0
            datastoreClusterName: jkt01-POC-DEV-DCS-01
            systemVolume: true
          - quantity: 100
            datastoreClusterName: jkt01-POC-DEV-DCS-01
            path: /var/lib/kubelet
            format: xfs
          - quantity: 100
            datastoreClusterName: jkt01-POC-DEV-DCS-01
            path: /var/lib/containerd
            format: xfs
      ipHostPoolRef:
        name: dcs-workloadcluster-worker-ippool
